db:
  conn_url: postgresql://{user}:{pwd}@{host}/{database}
  host: localhost
  user: tns
  database: tns
  pwd: tns#1
  schema: public

app:
  elite_rss_feed_uri: https://rankings.the-elite.net/all-prs.rss
  crypto_key: /Users/vitor/sandbox/tns/tns.key
